# Name of workflow
name: PHP CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        # Action gives to setup the PHP environment to test application
      - uses: actions/checkout@main
        with:
          # Specify the PHP version
          php-version: '8.0'
          fetch-depth: 1
      - name: Install
        # Install project
        run: make install
      - name: Run linter
        # Run Linter
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make lint
